_welcome:
    pattern:  /
    defaults: { _controller: AcmeTiaociBundle:Welcome:index }

_demo_secured:
    resource: "@AcmeTiaociBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeTiaociBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo
