_demo_secured:
    resource: "@AcmeTiaociBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeTiaociBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

_index:
    pattern:  /
    defaults: { _controller: AcmeTiaociBundle:Index:index }

_admin_index:
    pattern: /admin/index
    defaults: { _controller: AcmeTiaociBundle:Admin:index }
